    apiVersion: skaffold/v2beta12
    kind: Config
    deploy:
      kubeContext: minikube
      kubectl:
        manifests:
          - ./k8s/*
    build:
      local:
        push: false
      artifacts:
        - image: scottbeaman/multi-client
          context: client
          docker:
            dockerfile: Dockerfile.dev
          sync:
            manual:
              - src: "src/**/*.js"
                dest: .
              - src: "src/**/*.css"
                dest: .
              - src: "src/**/*.html"
                dest: .
        - image: scottbeaman/multi-worker
          context: worker
          docker:
            dockerfile: Dockerfile.dev
          sync:
            manual:
              - src: "*.js"
                dest: .
        - image: scottbeaman/multi-server
          context: server
          docker:
            dockerfile: Dockerfile.dev
          sync:
            manual:
              - src: "*.js"
                dest: .